--DDL for Category Table
CREATE TABLE IF NOT EXISTS category (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code INTEGER NOT NULL,
    name varchar(255),
    creation_date date,
    CONSTRAINT category_pkey PRIMARY KEY (id),
    CONSTRAINT uq_category_code UNIQUE (code)
);

-- Products table
CREATE TABLE IF NOT EXISTS product (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY
        ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    code BIGINT NOT NULL,
    name varchar(255),
    category_code INTEGER NOT NULL,
    creation_date date,
    CONSTRAINT product_pkey PRIMARY KEY (id),
    CONSTRAINT uq_product_code UNIQUE (code),
    CONSTRAINT fk_product_category FOREIGN KEY (category_code)
        REFERENCES category (code)
);

